services:
  postgresql:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./demo-small-en.sql:/docker-entrypoint-initdb.d/demo-small-en.sql
